# Generated by Django 3.2.6 on 2021-08-10 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('data_nasc', models.DateTimeField()),
                ('nacionalidade', models.CharField(max_length=50)),
                ('sexo', models.IntegerField(choices=[(1, 'Masculino'), (2, 'Feminino')])),
            ],
        ),
        migrations.CreateModel(
            name='Editora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cidade', models.CharField(max_length=150)),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('qtd_paginas', models.IntegerField()),
                ('ano_pub', models.IntegerField()),
                ('resenha', models.TextField()),
                ('autor', models.ManyToManyField(to='livros.Autor')),
                ('editora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livros.editora')),
            ],
        ),
    ]
