# Generated by Django 3.2.6 on 2021-08-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='capa_livro',
            field=models.ImageField(blank=True, upload_to='capas/%d/%m/%Y'),
        ),
    ]
